language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm run test-with-coverage
env:
  matrix:
    secure: N/YJSuhzOs2+uCw/XsQRnT4qwfGfrrHq5Rp4qSve19MTjklWj2i+I6+U4eyBaukDqcez/WkJxsLq0ebqRM1YQ2MRr8gOw6xs/iC4iiLMS0XXbavpaJ9olvp2saS/JNYTt0PwUkMP4qwmTA1v9IxTV423O2XchkSJ053Gr7CcMTYWS55fDadHbAbqD4wMwdFG7XcVmxdG3RHT5cVI6iWJJfMTmETlD6jtAydPHLR0jAJpyuyEmkykGuKCH5Z6zlGDHFnBwPe48Fm8DNYu1cyUSrJ8GXV5CJNDQ5l0kgILC56e7yttlF5+an3XqpOv0008cvu9lYNaKR6sBE5x6q/CqA8kmAr/tyzO0s64/qQOgLyEmxFM4lINrqnoJl0L28NY4E+Rvs3cmXlX/l397C/+lgEKTxwHuPYXIpugE0uvs/Lzdn5k8dz1xbKiu7cHf7j1kMOB0H8sK8gO6h6vH6GL1+CmCFxXF4TrLLdb5IOGSGRI2RqLpMEPe/fonOCPOB4Yk4vV0x2rz1QZUJoZjz8OYMEKArENSq54gKQvFI3LgLatyMcoEMGCeLhd4VgoIkRHAM/jsc4EbtC6ZqxT1uXh+XCL5Eoja+mK6rzZmoBRysEUI1Rh/yF9n4Yibor5DvjrMrml1nXIl1mtd50y/YwVQi5aeMKD6vsQ85mH1eQEyr0=
